channels:
  - pytorch 
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pip=23.2.1
  - pandas=2.2.0
  - numpy=1.25.2
  - networkx=3.1
  - matplotlib=3.7.2
  - dash=2.15.0
  - dash-bootstrap-components=1.5.0
  - biopython=1.81
  - goatools=1.3.1
  - scipy=1.11.1
  - seaborn=0.12.2
  - statsmodels=0.14.0
  - UpSetPlot=0.8.0
  - diamond=2.0.14
